#ifndef CPP2_S21_CONTAINERS_1_SRC_CONTAINERS_S21_CONTAINERSPLUS_H_
#define CPP2_S21_CONTAINERS_1_SRC_CONTAINERS_S21_CONTAINERSPLUS_H_

#define MAX_MEMORY ((~(size_t)0) >> 1)

#include "array/s21_array.h"
#include "multiset/s21_multiset.h"

#endif  // CPP2_S21_CONTAINERS_1_SRC_CONTAINERS_S21_CONTAINERSPLUS_H_